
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://diyamtmjxdcjptbcslmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpeWFtdG1qeGRjanB0YmNzbG16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2Njc0NTUsImV4cCI6MjA1NjI0MzQ1NX0.6Ne3E4AGW9EBNoWS38W3rsIsStjmuA5BdXQ582uxi6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Check if storage buckets exist and create them if they don't
(async () => {
  try {
    const { data: buckets } = await supabase.storage.listBuckets();
    const avatarBucketExists = buckets?.some(bucket => bucket.name === 'avatars');
    const roomProfileBucketExists = buckets?.some(bucket => bucket.name === 'room-profile-pics');
    
    if (!avatarBucketExists) {
      console.log('Creating avatars bucket...');
      // Note: In a production app, we would create this bucket through SQL migrations
      // This is just for development convenience
      await supabase.storage.createBucket('avatars', {
        public: true,
        fileSizeLimit: 1024 * 1024 * 2 // 2MB
      });
    }
    
    if (!roomProfileBucketExists) {
      console.log('Creating room-profile-pics bucket...');
      await supabase.storage.createBucket('room-profile-pics', {
        public: true,
        fileSizeLimit: 1024 * 1024 * 2 // 2MB
      });
    }
  } catch (error) {
    console.error('Error checking/creating storage buckets:', error);
  }
})();

// Removed duplicate export here
