// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://diyamtmjxdcjptbcslmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpeWFtdG1qeGRjanB0YmNzbG16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2Njc0NTUsImV4cCI6MjA1NjI0MzQ1NX0.6Ne3E4AGW9EBNoWS38W3rsIsStjmuA5BdXQ582uxi6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);